name: Add PR Labels

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: nodejs/node-pr-labeler@v1
        with:
          configuration-path: .github/PR_LABELS_FILE.yml
      - uses: TimonVS/pr-labeler-action@v3
        with: 
         configuration-path: .github/PR_LABELS_BRANCH.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
